name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: pip install -r requirements.txt
      
    - name: Deploy to EC2
      run: |
        echo "$PRIVATE_KEY" > deploy_key.pem
        chmod 600 deploy_key.pem
        ssh-keyscan -H 3.111.170.198 >> ~/.ssh/known_hosts
        scp -i deploy_key.pem -r . ec2-user@3.111.170.198:/home/ubuntu
        ssh -i deploy_key.pem ec2-user@3.111.170.198 'cd /home/ubuntu && python app.py'
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
