name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Deploy to EC2
        run: |
          scp -i /home/ubuntu/firstkey.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r . ec2-user@3.111.170.198:/home/ubuntu
          ssh -i /home/ubuntu/firstkey.pem ec2-user@3.111.170.198 'cd /home/ubuntu && python app.py'
